config/routes.rb
Rails.application.routes.draw do
  resources :articles

  resources :users
  root 'users#new'
  resources :sessions, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

validates :title, presence: true, length: {minimum: 5, maximum: 50}
validates :description, presence: true, length: {minimum: 10, maximum: 100}
belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

validates :name, presence: true,
uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :email, presence: true, length: {maximum: 50},
uniqueness: {case_sensitive: false}, format: { with: VALID_EMAIL_REGEX}

has_secure_password

has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception

helper_method :current_user, :logged_in?

def current_user

@current_user ||= User.find(session[:user_id]) if session[:user_id]

end

def logged_in?
	!!current_user
end

def require_user
	if !logged_in?
		flash[:danger] = "You must be logged in to perform that action"
		redirect_to new_session_path
	end
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:show, :edit, :update, :destroy, :index, :new, :create]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end

def create
user = User.find_by(email: params[:session][:email].downcase)
if user && user.authenticate(params[:session][:password])
session[:user_id] = user.id
flash[:success] = "You have successfully logged in"
redirect_to user_path(user)
else
flash.now[:danger] = "There was something wrong with your login information"
render 'new'
end
end

def destroy
session[:user_id] = nil
flash[:success] = "You have logged out"
redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:show, :edit, :update, :index, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @articles = @user.articles
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_articles.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%#= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %>  |</td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>
<% if @article.errors.any? %>
<h2>Following errors prevented from article getting created</h2>
<ul>
	<% @article.errors.full_messages.each do |msg| %>
	<li> <%= msg %> </li>
	<% end %>
</ul>
<% end %>
<%= render 'form', article: @article %>

<%#= link_to 'Show', current_user %>
<%= link_to 'Back', current_user %> |
<%= link_to 'Delete', @article, method: :delete, data: {confirm: "Are you sure?"} %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

<%= link_to 'Profile', users_path %>

app/views/articles/new.html.erb
<%# if @articles.errors.any? %>
<ul>
	<% @article.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<%# end %>
<h2>New Article</h2>

<%= render 'form', article: @article %>

<%= link_to 'Back', current_user %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <ul>
      <li><%=msg %></li>
    </ul>
    <% end %>
    

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav navbar-right">

<% if logged_in? %>

<li><%= link_to 'Log out', logout_path, method: :delete %></li>

<li class="dropdown">

<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>

<ul class="dropdown-menu">

<li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>

<li><%= link_to "View your profile", user_path(current_user) %></li>

<li><a href="#">Something else here</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">Separated link</a></li>

</ul>

</li>

<% else %>

<li><%= link_to 'Log in', login_path %></li>

<li><%= link_to 'Sign up', signup_path %></li>

<% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <div class="ui inverted menu">
      <div class="ui container">
        <%= link_to 'Home', current_user, class: "item" %>
        <%= link_to 'Users', users_path, class: "item" %>
        <div class="right menu">
          <div class="ui dropdown item">
            Account <i class="dropdown icon"></i>
            <div class="menu">
              <%= link_to 'Edit profile', edit_user_path(current_user), class: "item" %>
              <a class="item">xyz</a>
              <a class="item">abc</a>
            </div>
          </div>
          <div class="menu">
            <%#= link_to 'Log out', logout_path, method: :delete %>
            <%= link_to 'Log out', logout_path, method: :delete, class: "item" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit "Sign up", class: "ui blue submit button" %>
  
<% end %>
</div></div>
<div class="middle aligned column">
      
        <%= link_to 'Login', new_session_path, class: "ui blue submit button" %>
      </div>
    </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>
  </div>

app/views/users/edit.html.erb
<h1 align="center">Edit User</h1>

<%#= render 'shared/errors', obj: @user %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1 align="center">Welcome to Alpha Blog</h1>

<%#= render 'shared/errors', obj: @user %>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="ui segment">
  <div class="ui two column very relaxed grid">
    <div class="column">
<p id="notice"><%= notice %></p>
<h1>User</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<%= link_to 'New article', new_article_path %> |
<%= link_to 'Back', users_path %>

<br>
<%= render 'articles/articles' %>
</div>
<div class="column">
	<h2>Chat</h2>
	</div>
</div>
<div class="ui vertical divider">|</div></div>